markdown: kramdown
title: Furycord
slogan: How To Train Your Dragon - On Discord!
description: How To Train Your Dragon - On Discord!

color: 8B4513

copyright: How To Train Your Dragon © 2018 DreamWorks Animation LLC. All Rights Reserved.