markdown: kramdown
title: Furycord
slogan: How To Train Your Dragon - On Discord!
description: Bringing "How To Train Your Dragon" to your Discord Server!

color: 8B4513

copyright: How To Train Your Dragon © 2018 DreamWorks Animation LLC. All Rights Reserved.